### ISSUE TITLE
entry.data can be null

### ISSUE THREAD

**Issue by vincentjames501** [ChrLipp/notes-import#1]
This tool was a lifesaver. Thanks! One thing I bumped into though (at least for my database) was one of the entries' data was `null` and caused an NPE. May not be bad to just tweak this slightly:

```groovy
entries.each { entry ->
  if (entry.data) {
    def output = new File("output/${entry.key}.txt")
    output.text = getPlainText(decompress(entry.data)).trim()
  }
}
```

Thanks again!

**Comment by ChrLipp** [comment]
Glad to hear this code is useful (even when it is executed only once), thanks a lot! Applied your suggestion - thanks for the hint!
